public class intrest_1504_class {
    public integer amn {set;get;}
    public integer intrest {set;get;}
     public integer tim {set;get;}
     public integer ti {set;get;}
     public integer awi {set;get;}
    public integer result1 {set;get;}
    public integer result2 {set;get;}
    
    
    
   public void intrestcaluculation() {
        ti=(amn*intrest*tim)/100;
        awi=ti+amn;
       result1=ti;
       result2=awi;
        
    }
    

}